# This is a basic workflow to help you get started with the Pull request comment action.

name: Example

# Controls when the workflow will run
# This workflow does only support running on PR. 
on:
  pull_request:
    branches: ["main"]

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Add a comment to the PR
        uses: Libra-foundation/Pull-Request-Comments@V1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: templates/template.md
